apiVersion: apps/v1
kind: Deployment

metadata:
  name: gamers-island
  namespace: karni2407

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gamers-island

  template:
    metadata:
      labels:
        app: gamers-island

    spec:
      containers:
      - name: gamers-island
        image: karni2407/gamers-island:latest

        ports:
        - containerPort: 8000

        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: games-config
              key: ENV

        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: games-config
              key: ALLOWED_HOSTS
