apiVersion: v1
kind: Service

metadata:
  name: exam-portal-service
  namespace: karni2407

spec:
  type: NodePort

  selector:
    app: exam-portal

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
