apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo Hello Kubernetes > /data/message.txt && sleep 3600"]
      volumeMounts:
        - name: my-storage
          mountPath: /data

  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: demo-pvc
