apiVersion: v1
kind: Service

metadata:
  name: blog-svc
  namespace: karni2407

spec:
  type: NodePort

  selector:
    app: django-blogger

  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
